ua-eas/kfsdbupgrade

src/main/resources/upgrade-files/3.0.1_4.0/rice/kim_upgrade.xml
src/main/resources/upgrade-files/3.0.1_4.0/rice/kim_upgrade_mod.xml
src/main/resources/upgrade-files/4.0_4.1/rice/kim_security_module.xml
src/main/resources/upgrade-files/4.1.1_5.0/rice_server/kim_upgrade.xml
src/main/resources/upgrade-files/4.1.1_5.0/rice_server/kim_upgrade_mod.xml
src/main/resources/upgrade-files/5.0.2_5.0.3/rice_server/kim_upgrade.xml
src/main/resources/upgrade-files/5.0.5_5.1/rice_server/kim_upgrade.xml
src/main/resources/upgrade-files/5.0.5_5.1/rice_server/kim_upgrade_mod.xml
src/main/resources/upgrade-files/5.0_5.0.1/rice_server/kim_upgrade.xml
src/main/resources/upgrade-files/5.0_5.0.1/rice_server/kim_upgrade_mod.xml
src/main/resources/upgrade-files/5.1.2_5.2/rice_server/kim_upgrade.xml
src/main/resources/upgrade-files/5.1.2_5.2/rice_server/kim_upgrade_mod.xml
src/main/resources/upgrade-files/5.2.2_5.3/rice_server/kim_upgrade.xml
src/main/resources/upgrade-files/5.3.2_5.4/rice_server/kim_upgrade.xml

Updated upgrade scripts. Commented out lines where the permission was being assigned to a foundation role and there is no UA Specific role at this time.  Updated the foundation role_id to the UA specific role.
Updated both the normal xml file and the "mod" xml files.

UAF-936 DB Upgrade Script - Assign New 6.0 Permissions to Correct Roles

---

src/main/resources/kfsdbupgrade.properties
src/main/resources/upgrade-files/post-upgrade/sql/add_lookup_records_permission.sql

UAF-2070 : Add 'Lookup Records' Permission to the KFS-PDP UA Check Control Role in DB Upgrade Script. Added 'post-upgrade/sql/add_lookup_records_permission.sql' file to Add 'Lookup Records' Permission to the KFS-PDP UA Check Control Role to table "KRIM_ROLE_PERM_T"; modified file '/kfsdbupgrade/src/main/resources/kfsdbupgrade.properties' to invoke it.

UAF-2070 : Add 'Lookup Records' Permission to the KFS-PDP UA Check Control Role in DB Upgrade Script. 

---

src/main/resources/kfsdbupgrade.properties
src/main/resources/upgrade-files/post-upgrade/sql/inactivate_role_11053.sql

UAF-2321 : Inactivate Redundant Role 11053 <Exclude Single Actor Separation Of Duties> in Upgrade Scripts. Created SQL script 'post-upgrade/sql/inactivate_role_11053.sql' file to; Update Role 11053: 1) inactivate the role, 2) inactivate responsibility 92 on the role, 3) inactivate Role 56 on the role by adding a current end date.

UAF-2321 : Inactivate Redundant Role 11053 in Upgrade Scripts.

---

src/main/resources/kfsdbupgrade.properties
src/main/resources/upgrade-files/post-upgrade/sql/add_responsibility_49_role_10403.sql

UAF-2739 : Activate Responsibility 49 and Add Responsibility 49 (Review KFS Tax) to Role 10403 (UA FSO AP Tax Specialists).  Added SQL script file 'post-upgrade/sql/add_responsibility_49_role_10403.sql' containing delete/update scripts and modified file '/kfsdbupgrade/src/main/resources/kfsdbupgrade.properties' to invoke it.

UAF-2739 : Activate Responsibility 49 to Role 10403 (UA FSO AP Tax Specialists)

---

src/main/resources/upgrade-files/post-upgrade/sql/UAF-2739_add_responsibility_49_role_10403.sql

UAF-2739 : Per Misty and AK, to match foundation data, removed last statement 'UPDATE KULOWNER.KRIM_RSP_ATTR_DATA_T SET ATTR_VAL = 'true' WHERE ATTR_DATA_ID IN ('159');' from 'src/main/resources/upgrade-files/post-upgrade/sql/UAF-2739_add_responsibility_49_role_10403.sql'

UAF-2739 : Per Misty and AK, to match foundation data, removed last statement.

---

src/main/resources/flowdown-files/sql/kfs6-env-flowdown.sql

Note: It is up to whatever calls the flowdown script (Jenkins job, human user) to hydrate the value for ${ENCRYPTION_KEY} safely.

UAFAWS-98 - Removing decryption function. Making encryption key parameterized.

---

src/test/java/ua/utility/kfsdbupgrade/IndexScriptExecutionTest.java

Adding "\@Ignore' tag to full index test method so that Jenkins can have it's JUnit precondition turned back on.

UAF-4749 Deactivating full index test, as UAF-2483 has the SQL fix.

---

src/main/resources/upgrade-files/post-upgrade/sql/UAF-4199Remove_Discontinued_Outbound_Messaging_MOD.sql

UAF-4199 : Removal of Doc Type, Parameters, Parm Components & Permission From Discontinued Outbound Messaging MOD. Subtask of (UAF-92). Added SQL DELETE script in 'kfsdbupgrade\src\main\resources\upgrade-files\post-upgrade\sql\UAF-4199Remove_Discontinued_Outbound_Messaging_MOD.sql'.

UAF-4199 : Removal of Doc Type, Parameters, Parm Components & Permission From Discontinued Outbound Messaging MOD.

---

src/test/java/ua/utility/kfsdbupgrade/IndexScriptExecutionTest.java

This should resolve conditions for UAF-4709 to be "confirmed", by changing one of (the last) integration JUnit methods to possess the "@Ignore" annotation.

UAF-4901 - Adding 'ignore' to integration JUnit.

---

src/main/resources/upgrade-files/4.1.1_5.0/db/03_constraints/fp-module-constraint-updates.xml

UAF-4240 : ERROR ua.utility.kfsdbupgrade.App : FP_PRCRMNT_CARD_DFLT_TR2: ORA-02291: integrity constraint violated - parent key not found.  Removed addition of constraint FP_PRCRMNT_CARD_DFLT_TR2 to prevent this error.

UAF-4240 : ERROR ua.utility.kfsdbupgrade.App : FP_PRCRMNT_CARD_DFLT_TR2: ORA-02291: integrity constraint violated - parent key not found.

---

src/main/resources/upgrade-files/4.0_4.1/db/01_structure/rice-client-structure.xml

UAF-4237 : KFS_401_RESTORE_MISSING_RICE_SEQUENCES. Uncommented Liquibase <preconditions > clause in '\kfsdbupgrade\src\main\resources\upgrade-files\4.0_4.1\db\01_structure\rice-client-structure.xml' to check whether sequence exists before trying to create it again. Modified Liquibase comment for greater log clarity.

UAF-4237 : KFS_401_RESTORE_MISSING_RICE_SEQUENCES

---

src/main/resources/flowdown-files/sql/kfs6-env-flowdown.sql

UAF-3028 : Change flowdown script so kfs-test-sys10 user permissions more accurately match policy. Modified 'kfsdbupgrade\src\main\resources\flowdown-files\sql\kfs6-env-flowdown.sql' kfs-test-sys10 insert account delegate statements' sub-selects to exclude accounts where user id('T000000000000003189') is a Fiscal Officer.

UAF-3028 : Change flowdown script so kfs-test-sys10 user permissions more accurately match policy. 

---

src/main/java/ua/utility/kfsdbupgrade/ForeignKeyReference.java

UAF-4243 : ERROR ua.utility.kfsdbupgrade.App :: failed to create index:: ORA-00972: identifier is too long.  Oracle versions before 12.2 only allow identifiers upto 30 characters in length. So shortening Index names by removing unnecessary characters from the table name used to construct the Index name.

UAF-4243 : Shorten Index names by shortening the Index name stub generated from a table name.

---

src/main/resources/flowdown-files/sql/kfs6-env-flowdown.sql

UAF-3028 : Change flowdown script so kfs-test-sys10 user permissions more accurately match policy. Modified 'kfsdbupgrade\src\main\resources\flowdown-files\sql\kfs6-env-flowdown.sql' kfs-test-sys10 insert account delegate statements' removed functionally redundant insert with 'KFST' fdoc_typ_cd parameter.

UAF-3028 : Change flowdown script so kfs-test-sys10 user permissions more accurately match policy

---

src/main/resources/flowdown-files/sql/kfs6-env-flowdown.sql

UAF-5403 : Modify Backdoor Access for KFS 6 & 7 Environments - swatts, pprokop, tounou. Added KFS 6 DB backdoor access permission SQL inserts for Shawn Clodfelter (swatts) and Pamela Prokop (pprokop) and Removed for Antoine Tounou (tounou) to kfsdbupgrade file 'flowdown-files/sql/kfs6-env-flowdown.sql'.

UAF-5403 : Modify Backdoor Access for KFS 6 & 7 Environments - swatts, pprokop, tounou. 

---

src/main/java/ua/utility/kfsdbupgrade/MaintainableXMLConversionServiceImpl.java

UAF-5089 : DBUpgrade: Please investigate Excessive WARN: Document has classname in contents that should have been mapped on 07/17/17.  Added code to 'ua.utility.kfsdbupgrade.MaintainableXMLConversionServiceImpl.transformSection()' to update old classnames not updated so far that occur in '<active defined-in=' tags.

UAF-5089 : DBUpgrade: Please investigate Excessive WARN: Document has classname in contents that should have been mapped on 07/17/17.

---

.gitignore
src/main/resources/upgrade-files/post-upgrade/sql/UAF-3849-bootstrap_new_gec_relationship_data.sql

This changes the 'naive' way of pulling fiscal year to instead use a special table for this purpose. This ensures all legacy data that should be considered, actually is being considered.

UAF-5099 - Changing how GEC bootstrap determines fiscal year; add IDE file to gitignore.

---

src/main/resources/flowdown-files/sql/kfs6-env-flowdown.sql

UAF-5455 : Modify Backdoor Access for KFS 6 & 7 Environments - tholan and tgonzale. Added KFS 6 DB backdoor access permission SQL inserts for Tara J Gonzales (tgonzale) and Tabatha M Holan (tholan) to kfsdbupgrade file 'flowdown-files/sql/kfs6-env-flowdown.sql'.

UAF-5455 : Modify Backdoor Access for KFS 6 & 7 Environments - tholan and tgonzale.

---

src/main/resources/upgrade-files/5.3.2_5.4/workflow/workflow_document_upgrades.xml

This should correct the errors generated by the child workflow referencing its-not-loaded-yet parent.

UAF-4657 - Adding missing parent doc type for kc-kfs module.

---

src/main/resources/MaintainableXMLUpgradeRules.xml

UAF-5504 : 3 to 6 KFSDBUpgrade - Investigate and Resolve Not yet Upgraded Maintenance Documents.  Applied maintenance document replacement patterns to '\kfsdbupgrade\src\main\resources\MaintainableXMLUpgradeRules.xml' for the following classes 'PaymentMaintainableImpl','PayeeMaintainableImpl','PRJEType','PRJEAccountLine','PRJEBaseObject','PRJESet','PRJEBaseAccount'.

UAF-5504 : 3 to 6 KFSDBUpgrade - Investigate and Resolve Not yet Upgraded Maintenance Documents. 

---

src/main/java/ua/utility/kfsdbupgrade/MaintainableXMLConversionServiceImpl.java
src/main/resources/MaintainableXMLUpgradeRules.xml

UAF-5698 : Investigate Errors for KFS 3 Shipping Docs Migrated to KFS 7. Modified file 'MaintainableXMLUpgradeRules.xml' with old class 'org.kuali.rice.kns.maintenance.KualiMaintainableImpl' to  new class 'org.kuali.kfs.sys.document.FinancialSystemMaintainable' pattern. Modified file 'MaintainableXMLConversionServiceImpl.java' to replace classes in attribute 'maintainableImplClass='.

UAF-5698 : Investigate Errors for KFS 3 Shipping Docs Migrated to KFS 7. 

---

src/main/java/ua/utility/kfsdbupgrade/MaintainableXMLConversionServiceImpl.java

UAF-5917 : Correct KFSDBUpgrade XML closing tag replacement. Corrected an error in  'ua.utility.kfsdbupgrade.MaintainableXMLConversionServiceImpl.transformSection' that was preventing replacement of closing tags eventhough opening tags were being replaced.

UAF-5917 : Correct KFSDBUpgrade XML closing tag replacement.

---

src/main/resources/flowdown-files/sql/kfs6-env-flowdown.sql

UAF-5938 : Modify Backdoor Access for UAF 7 Environments for vmolt. Added SQL Insert to files 'scripts/kfs6-env-flowdown.sql' and 'scripts/rice2.5-env-flowdown.sql' to enable Backdoor access for Victoria Molt (vmolt).

UAF-5938 : Modify Backdoor Access for UAF 7 Environments for vmolt.

---

src/main/resources/upgrade-files/post-upgrade/sql/UAF-3849-bootstrap_new_gec_relationship_data.sql

This PR removes all SQL that 'bootstrapped' legacy GEC data into a new relationship data. The intent is that v3 data will not have these relationships; post-golive, only new GECDs will get a relationship made (via v7 java code, real time).
This means this PR is only intended to change how data is handled, not that any new DB DDL should be removed. The java code still relies on the new tables and table columns on existing tables. Said another way, this PR has changes to DML, not any DDL.
Please see the associated jira for more information.

UAF-6062 - Removing logic that builds GEC relationships on KFSv3 data.

---

src/main/java/ua/utility/kfsdbupgrade/MaintainableXMLConversionServiceImpl.java

ACCT maintenance doc has EntityAddress change which is a reference object from Person. The way original code creating new EntityAddressBo, marshaling and appending to ACCT maint xstream will append a EntityAddress to the end of stream of Account BO node which can't map to Account BO since Account BO has no direct reference to EntityAddress. The fix is to remove appending EntityAddressBo node from ACCT xml since it's not directly referenced from Account. It can be derived from Person BO still since it's referred from Person BO after unmarshalling.

UAF-5951 Bug - Cannot open Account doc created in 3 in STG7

---

src/main/java/ua/utility/kfsdbupgrade/MaintainableXMLConversionServiceImpl.java
src/main/resources/MaintainableXMLUpgradeRules.xml

UAF-5564 : KFS7 STG Receive a Conversion STE When Attempting to View Enroute/Legacy 3.0 CASM Documents. Added AssetExtension upgrade properties to rule name='maint_doc_changed_class_properties' and subsidiary classes to rule name='maint_doc_classname_changes' of 'resources\MaintainableXMLUpgradeRules.xml'. Removed no longer needed AssetMaintainable classes from rule name='maint_doc_classname_changes' of 'resources\MaintainableXMLUpgradeRules.xml'. Modified 'kfsdbupgrade\MaintainableXMLConversionServiceImpl.java' 'transformSection' method to transform the properties of nested extension class attribute nodes.

UAF-5564 : KFS7 STG Receive a Conversion STE When Attempting to View Enroute/Legacy 3.0 CASM Documents.

---

src/main/java/ua/utility/kfsdbupgrade/MaintainableXMLConversionServiceImpl.java

The following changes fixes the following exception.  
```
**--- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
cause-message       : Cannot create type by JDK serialization
class               : org.kuali.rice.kim.framework.group.GroupEbo
required-type       : org.kuali.rice.kim.framework.group.GroupEbo
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /edu.arizona.kfs.fp.businessobject.ProcurementCardDefault/reconcilerGroup
line number         : 31
class[1]            : edu.arizona.kfs.fp.businessobject.ProcurementCardDefault
version             : 1.4.9**
```
*Note that the original exception mentioned in the UAF-5995 Jira  ` message  : No such field …

UAF-5995 BUG - MOD UAF-48 - Unable to view historic PCDM documents

---

src/main/resources/MaintainableXMLUpgradeRules.xml

**java.lang.IllegalArgumentException: invalid (blank) docTypeName** when trying to click on a Document Id in the PAAT doc search results.
To understand why the documents won't open, I ran the **SingleXmlUpgrader** against the several PAAT maintenance docs and found that the document still contained the **org.kuali.kfs.pdp.businessobject.PayeeACHAccount** as a node.  
Since the **PayeeACHAccount** is now in an edu.arizona package as explained in **https://github.com/ua-eas/financials/pull/113** , I added a rule in **MaintainableXMLUpgradeRules.xml** to replace the **org.kuali.kfs.pdp.businessobject.PayeeACHAccount** nodes in the XML with 
**edu.arizona.kfs.pdp.businessobject.PayeeACHAccount**.  I tested this rule on several documents and wrote them to the kfs7dev db.  The documents were …

UAF-6104 Bug - Cannot complete a search for PAAT doc type

---

src/main/resources/MaintainableXMLUpgradeRules.xml

UAF-3076 : Handle maintenance document xml upgrade for OrganizationExt. Modified 'MaintainableXMLUpgradeRules.xml' to replace class 'edu.arizona.kfs.coa.businessobject.OrganizationExt' with 'org.kuali.kfs.krad.bo.PersistableBusinessObjectExtensionBase' and remove properties 'organizationCode','chartOfAccountsCode','reportOrderCode'.

UAF-3076 : Handle maintenance document xml upgrade for OrganizationExt. 

---

src/main/resources/flowdown-files/sql/kfs6-env-flowdown.sql

UAF-6239 : Remove Backdoor Access for CeCe Wilson and Austin Morrell. Remerging this branch because previous merge was rolled back since accidentally done during code freeze.

UAF-6239 : Remove Backdoor Access for CeCe Wilson and Austin Morrell.

---

src/main/resources/MaintainableXMLUpgradeRules.xml

UAF-6338 : BUG - 3.0 CSCR document STE.  Added pattern to replace class 'com.rsmart.kuali.kfs.cr.businessobject.CheckReconciliation' with 'edu.arizona.kfs.module.cr.businessobject.CheckReconciliation' in file '\kfsdbupgrade\src\main\resources\MaintainableXMLUpgradeRules.xml'.

UAF-6338 : BUG - 3.0 CSCR document STE.  Added pattern to replace class 

---

src/main/resources/log4j.properties

This clears up hundreds of error and warning messages from this job. Please see the related jira for more details.

UAF-6485 - Adding log4j entries to suppress unimpactful errors/warnings.

---

src/main/resources/MaintainableXMLUpgradeRules.xml

Include rules to convert existing kfs3 TXPA,TXPM, TXPR documents so that they could be opened in kfs7.

UAF-6597 Convert TXPA, TXPM, TXPR

---

src/main/resources/MaintainableXMLUpgradeRules.xml

Along with Rice KNS separated to kfs-kns in KFS7, org.kuali.rice.krad.bo.KualiCodeBase.KualiCodeBase has been replaced in KFS7 by org.kuali.kfs.krad.bo.KualiCodeBase. Though KFS3->6, org.kuali.rice.kns.bo.KualiCodeBase was replaced by org.kuali.rice.krad.bo.KualiCodeBase.KualiCodeBase, we have to convert it to KFS7 class type, i.e.  org.kuali.kfs.krad.bo.KualiCodeBase directly in kfsdbupgrade.

UAF-6614 Convert ITYP (Indirect Cost Recovery Type)

---

src/main/resources/upgrade-files/post-upgrade/sql/UAF-6591.sql

Update the authorizer for PARNT_ID 329519.  The original logic to only update where the PARNT_ID is non-current would not work because at the point when these scripts are run, the PARNT_ID of 329519 would have been the most current and thus would not be affected by the updates.

UAF-6591 Convert CountyMaintenanceDocument, StateMaintenanceDocument, PostalCodeMaintenanceDocument, CountryMaintenanceDocument
