src/main/resources/flowdown-files/sql/kfs6-env-flowdown.sql, src/main/resources/kfsdbupgrade.properties, src/main/resources/upgrade-files/post-upgrade/sql/kfs-environment-flow.sql
Created folder to hold the KFS v6 flowdown script and added the new sql file for the flowdown to that folder.
=> UAF-371 Implement Solution To Run KFS 6 Flowdown Script Against A Target Database

src/main/resources/upgrade-files/5.4.1_6.0/db/01_structure/endow-module-structure-updates.xml
Commented out changesets for dropping foreign keys for those tables that do not have foreign keys. Commented out the DropForeignKeyConstraint for foreign keys that do not exist in tables that have foreign keys.
=> UAF-241 Investigate 6.0 Database Script Issues : Endowment Module

dependency-reduced-pom.xml, src/main/java/ua/utility/kfsdbupgrade/App.java, src/main/resources/kfsdbupgrade.properties, src/main/resources/upgrade-files/pre-upgrade/sql/krim-perm-name-updates.sql
UAF-2826 includes: UAF-2786 'Replace writeouts to System.out with logging' and code review recommendations and includes UAF-2826 'Remove permission name change in pre-upgrade Scripts lines 270 & 201'
=> UAF-2826 includes: UAF-2786 'Logging' and UAF-2826 'Pre-upgrade Scripts removals'

pom.xml, src/main/java/ua/utility/kfsdbupgrade/App.java, src/main/java/ua/utility/kfsdbupgrade/MaintainableXMLConversionServiceImpl.java
UAF-2787: Added exception logging with variable details to App.java and MaintainableXMLConversionServiceImpl.java, used wrap and re-throw pattern per review.
=> UAF-2787: Added exception logging with variable details to App.java and MaintainableXMLConversionServiceImpl.java 

src/main/resources/kfsdbupgrade.properties, src/main/resources/upgrade-files/post-upgrade/sql/update_phase_2_parameters.sql
UAF-2043 : Update Phase 2 Parameters in Upgrade Scripts.  Added 'post-upgrade/sql/update_phase_2_parameters.sql' file to update parameters in table 'KRCR_PARM_T'; modified file '/kfsdbupgrade/src/main/resources/kfsdbupgrade.properties' to invoke it.
=> UAF-2043 : Update Phase 2 Parameters in Upgrade Scripts

src/main/resources/kfsdbupgrade.properties, src/main/resources/upgrade-files/post-upgrade/sql/update_system_enhancement_parameters.sql
UAF-2924 : Update Parameters related to system enhancements. Added SQL script file 'post-upgrade/sql/update_system_enhancement_parameters.sql' containing update scripts and modified file '/kfsdbupgrade/src/main/resources/kfsdbupgrade.properties' to invoke it.
=> UAF-2924 : Update Parameters related to system enhancements.

src/main/resources/kfsdbupgrade.properties, src/main/resources/upgrade-files/post-upgrade/sql/update_requisition_source.sql
UAF-2471 : Update (PMSO) Requisition Source Maintenance Table Values in Database Script. Added SQL script file 'post-upgrade/sql/update_requisition_source.sql' containing update script and modified file '/kfsdbupgrade/src/main/resources/kfsdbupgrade.properties' to invoke it.
=> UAF-2471 : Update (PMSO) Requisition Source Maintenance Table Values in Database Script.

src/main/resources/kfsdbupgrade.properties, src/main/resources/upgrade-files/post-upgrade/sql/update_disbursement_voucher_payment_reason.sql
UAF-2745 : Update Disbursement Voucher Payment Reason(FP) Table.  Added SQL script file 'post-upgrade/sql/update_disbursement_voucher_payment_reason.sql' containing update script and modified file '/kfsdbupgrade/src/main/resources/kfsdbupgrade.properties' to invoke it.
=> UAF-2745 : Update Disbursement Voucher Payment Reason(FP) Table.

src/main/java/ua/utility/kfsdbupgrade/App.java, src/main/resources/upgrade-files/4.1.1_5.0/db/01_structure/fp-module-structure-updates.xml, src/main/resources/upgrade-files/4.1.1_5.0/db/01_structure/fp-module-structure-updates_mod.xml
Reverts ua-eas/kfsdbupgrade#86
=> Revert "UAF-2494: Adding additional columns to FP_PRCRMNT_CARD_DFLT_T and cha…"

src/main/resources/upgrade-files/post-upgrade/sql/UAF-3060_update_purchase_order_contract_part_2.sql
UAF-3060:Update Purchase Order Contract Language Maintenance Table (PMCL) Part 2.  Added hard newline characters(chr(10)) in SQL to format text.
=> UAF-3060:Update Purchase Order Contract Language Maintenance Table Part 2.

src/main/java/ua/utility/kfsdbupgrade/App.java, src/main/resources/MaintainableXMLUpgradeRules.xml, src/main/resources/upgrade-files/4.1.1_5.0/db/01_structure/fp-module-structure-updates.xml, src/main/resources/upgrade-files/4.1.1_5.0/db/01_structure/fp-module-structure-updates_mod.xml
-> Adding additional columns to FP_PRCRMNT_HLDR_DFLT_T
-> Updating name for maintenance doc from the old KFS3 rsmart ProcurementCardHolderDetails to ProcurementCardDefault
=> UAF-2492, UAF-2803: Making related changes to ProcurementCardDefault

src/main/resources/upgrade-files/post-upgrade/sql/UAF-3060_update_purchase_order_contract_part_2.sql
UAF-3060:Update Purchase Order Contract Language Maintenance Table (PMCL) Part 2.  Removed extra newline characters(chr(10)) in line 2a.
=> UAF-3060:Update Purchase Order Contract Language Maintenance Table Part 2

src/main/java/ua/utility/kfsdbupgrade/MaintainableXMLConversionServiceImpl.java
This is similar to the change that was made for UAF-3071.
=> UAF-4718 Substituting problematic character with a blank space

src/main/java/ua/utility/kfsdbupgrade/App.java
UAF-4999 : 6.0 BUG - 3.0 PO Documents Missing Doc Status on Returned Search Results.  Added methods to 'app.java' to insert dcoument statuses for: Vendor Credit Memo, Payment Request, Purchase Order, Line Item Receiving and Purchase Requistion.
=> UAF-4999 : 6.0 BUG - 3.0 PO Documents Missing Doc Status on Returned Search Results.

src/main/resources/MaintainableXMLUpgradeRules.xml
UAF-34 : MOD-FP0023-01 Automatic Prorate Journal Entries (PRJE). Updated PRJE ClassName <replacement> values in 'MaintainableXMLUpgradeRules.xml'.
=> UAF-34 : MOD-FP0023-01 Automatic Prorate Journal Entries (PRJE).

src/main/java/ua/utility/kfsdbupgrade/App.java, src/main/java/ua/utility/kfsdbupgrade/MaintainableXMLConversionServiceImpl.java, src/main/java/ua/utility/kfsdbupgrade/SingleXmlUpgrader.java, src/main/resources/MaintainableXMLUpgradeRules.xml, src/test/java/ua/utility/kfsdbupgrade/MaintainableXMLConversionServiceImplTest.java
UAF-34 : MOD-FP0023-01 Automatic Prorate Journal Entries (PRJE). Surfaced DocId to console logging throughout to expedite diagnosis of future missed classNames. Added class replacements of opening and closing XML tags to 'MaintainableXMLConversionServiceImpl.java'.
=> UAF-34 : MOD-FP0023-01 Automatic Prorate Journal Entries (PRJE). For KFSDBUpgrade.

src/main/resources/flowdown-files/sql/kfs6-env-flowdown.sql
UAF-5866 : Remove Mike Wellman and Ajeesh Gopinathan's Backdoor Login Access. Removed Backdoor access SQL Inserts for Mike Wellman and Ajeesh Gopinathan from file 'flowdown-files/sql/kfs6-env-flowdown.sql'.
=> UAF-5866 : Remove Mike Wellman and Ajeesh Gopinathan's Backdoor Login Access.

src/main/resources/flowdown-files/sql/kfs6-env-flowdown.sql
UAF-5966 : Modify Backdoor Access for UAF 7 Environments for cecewilson, robertafrench & deniseblum. Added SQL INSERTs to file 'flowdown-files/sql/kfs6-env-flowdown.sql' to enable Backdoor access for: Celia Wilson (cecewilson), Roberta French (robertafrench) and Denise Blum (deniseblum).
=> UAF-5966 : Modify Backdoor Access for UAF 7 Environments for cecewilson, robertafrench & deniseblum. 

src/main/resources/flowdown-files/sql/kfs6-env-flowdown.sql
Remove backdoor insert SQL associated with CeCe Wilson and Austin Morrell.
=> UAF-6239 Remove Backdoor Access for CeCe Wilson and Austin Morrell

src/main/resources/flowdown-files/sql/kfs6-env-flowdown.sql
Reverts ua-eas/kfsdbupgrade#198 .    Ooops!  I accidentally merged this pull requests during the code freeze so I'm creating this REVERT pull request to revert these changes.
=> Revert "UAF-6239 Remove Backdoor Access for CeCe Wilson and Austin Morrell"

src/main/resources/MaintainableXMLUpgradeRules.xml
Applied conversion rule for SOFTYP  which was UA MOD and contributed to org package.
=> UAF-6599 Convert SOFTYP (Source of Funds)

src/main/resources/MaintainableXMLUpgradeRules.xml
AssetTransactionType has moved from cab to cam to retire cab by vanilla KFS7.
=> UAF-6612 Convert PMTT (Asset Transaction Type)

pom.xml, src/main/java/org/kuali/kfs/coa/businessobject/SourceOfFunds.java, src/main/java/org/kuali/kfs/integration/cam/CapitalAssetManagementAssetTransactionType.java, src/main/java/org/kuali/kfs/module/cam/businessobject/AssetTransactionType.java
Copied missing KFS class to project to solve ClassNotFoundException, including, 
1. org.kuali.kfs.module.cam.businessobject.AssetTransactionType
2. org.kuali.kfs.coa.businessobject.SourceOfFunds
3. org.kuali.kfs.integration.cam.CapitalAssetManagementAssetTransactionType.java (reference class)
4. kfs-kns.jar of current version 7.20170323-ua-release41 which is dependency class of #1 and #2 .
=> UAF-6599 Fixed KFS class not found issue

src/main/java/ua/utility/kfsdbupgrade/MaintainableXMLConversionServiceImpl.java
Adding logic that essentially skips a portion of the ECRD xml from getting modified or pruned, which was the root cause of this issue.
=> UAF-6605 - Adding logic to correct ECRD maintenance xml.
